import os
import re
import random
import pickle

import pandas as pd
import nltk
from nltk.corpus import stopwords
from zeyrek import MorphAnalyzer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, accuracy_score


from collections import Counter




yorumlar = [
    ("Araba gerçekten çok konforlu ve sessiz.", "positive"),
    ("Müşteri hizmetleri çok yardımcı oldu, teşekkür ederim.", "positive"),
    ("Satış temsilcisi çok ilgiliydi.", "positive"),
    ("Araç iç tasarımı çok şık ve modern.", "positive"),
    ("Fiyat performans açısından gayet başarılı.", "positive"),
    ("Sürüş deneyimi gerçekten harikaydı.", "positive"),
    ("Yol tutuşu çok güven veriyor.", "positive"),
    ("İç mekân malzeme kalitesi çok iyi.", "positive"),
    ("Navigasyon sistemi çok işlevsel.", "positive"),
    ("Kliması hızlı soğutuyor, çok memnunum.", "positive"),
    ("Bluetooth bağlantısı sorunsuz çalışıyor.", "positive"),
    ("Multimedya ekranı oldukça kullanışlı.", "positive"),
    ("Aracın motor sesi neredeyse hiç yok.", "positive"),
    ("Yedek parça hemen temin edildi.", "positive"),
    ("Servis hizmeti oldukça hızlıydı.", "positive"),
    ("Test sürüşü sonrası hemen satın aldım.", "positive"),
    ("Geri görüş kamerası çok net gösteriyor.", "positive"),
    ("Kolay park edilebilen kompakt bir araç.", "positive"),
    ("Aracın rengi çok dikkat çekici.", "positive"),
    ("Uzun yolda yormayan bir sürüşü var.", "positive"),
    ("Koltuklar yumuşak ve destekli.", "positive"),
    ("Fren sistemi çok güvenli hissi veriyor.", "positive"),
    ("İç mekân aydınlatması göz yormuyor.", "positive"),
    ("Direksiyon çok yumuşak ve kolay kontrol ediliyor.", "positive"),
    ("Ses sistemi çok kaliteli.", "positive"),
    ("Araç beklentimin çok üstünde çıktı.", "positive"),
    ("Garanti süresi oldukça uzun.", "positive"),
    ("Serviste bekleme süresi çok kısaydı.", "positive"),
    ("Yetkili bayi çok yardımcı oldu.", "positive"),
    ("Araç çok az yakıyor, ekonomik.", "positive"),
    ("Güvenlik özellikleri çok gelişmiş.", "positive"),
    ("Hava yastıkları konumlandırması çok başarılı.", "positive"),
    ("Sunroof harika bir hava katmış.", "positive"),
    ("Otomatik park sistemi çok işe yarıyor.", "positive"),
    ("Tasarımı çok estetik, dikkat çekiyor.", "positive"),
    ("Yeni nesil multimedya sistemi çok hızlı.", "positive"),
    ("Uygulama ile aracı kontrol edebilmek harika.", "positive"),
    ("Kolayca randevu alabildim, sistem başarılı.", "positive"),
    ("Mobil uygulama üzerinden her şey izlenebiliyor.", "positive"),
    ("Aracın rengi gün ışığında çok hoş duruyor.", "positive"),
    ("Koltuk ısıtma özelliği çok konforlu.", "positive"),
    ("Şehir içinde manevra kabiliyeti çok yüksek.", "positive"),
    ("Otomatik vites geçişleri çok yumuşak.", "positive"),
    ("Sıfır araçta hiçbir kusur çıkmadı.", "positive"),
    ("Tasarımı ve teknolojisi çok uyumlu.", "positive"),
    ("Sürücü asistan sistemleri güven veriyor.", "positive"),
    ("Özelleştirilebilir ekranlar çok kullanışlı.", "positive"),
    ("Telefonla entegrasyonu çok kolay oldu.", "positive"),
    ("Aracın iç hacmi çok geniş.", "positive"),
    ("Kullanım kılavuzu çok açıklayıcıydı.", "positive"),
    ("Motor performansı beklentimin üstünde.", "positive"),
    ("Yakıt tüketimi beklediğimden daha az.", "positive"),
    ("Farlar gece sürüşü için oldukça yeterli.", "positive"),
    ("Araç sessiz çalışıyor, motor sesi rahatsız etmiyor.", "positive"),
    ("İç mekân kokusu çok ferah ve hoş.", "positive"),
    ("Aile kullanımı için çok uygun bir araç.", "positive"),
    ("Yokuş kalkış desteği çok işe yarıyor.", "positive"),
    ("Fren mesafesi çok kısa, güven veriyor.", "positive"),
    ("Geniş bagaj hacmi çok işime yaradı.", "positive"),
    ("Araç içinde hissedilen kalite çok yüksek.", "positive"),
    ("Direksiyon ısıtması kış için çok faydalı.", "positive"),
    ("Satın alma süreci çok hızlı ilerledi.", "positive"),
    ("Yetkili servis çok ilgiliydi.", "positive"),
    ("Beklentimi tam olarak karşıladı.", "positive"),
    ("Koltuklar ergonomik ve bel destekli.", "positive"),
    ("Aracın viraj performansı harika.", "positive"),
    ("Uzun yolda çok rahat ettim.", "positive"),
    ("Süspansiyon sistemi yolları hissettirmiyor.", "positive"),
    ("Motorun çekişi çok güçlü.", "positive"),
    ("Kolayca hızlanıyor, atik bir araç.", "positive"),
    ("Multimedya sistemi çok eğlenceli.", "positive"),
    ("Harita sistemi çok güncel ve doğru.", "positive"),
    ("Arka koltuklar da oldukça geniş.", "positive"),
    ("Aydınlatma sistemi çok etkileyici.", "positive"),
    ("Cam tavan çok hoş bir hava katıyor.", "positive"),
    ("Uzaktan çalıştırma özelliği çok pratik.", "positive"),
    ("İnternet bağlantısı hızlı ve stabil.", "positive"),
    ("Kablosuz şarj sistemi çok işlevsel.", "positive"),
    ("Yeni model teknolojik olarak çok gelişmiş.", "positive"),
    ("Yol bilgisayarı detaylı veri sunuyor.", "positive"),
    ("Motor sesi dışarıda bile az duyuluyor.", "positive"),
    ("Yeni modeldeki değişiklikler çok yerinde.", "positive"),
    ("Gösterge paneli çok okunaklı.", "positive"),
    ("Kör nokta uyarı sistemi çok işe yarıyor.", "positive"),
    ("Çocuk koltuğu bağlantıları çok pratik.", "positive"),
    ("Arka görüş aynası otomatik kararıyor.", "positive"),
    ("Ekran parlaklığı ideal seviyede.", "positive"),
    ("Araç içi ambiyans aydınlatması çok şık.", "positive"),
    ("Koltuk hafızası özelliği çok işime yaradı.", "positive"),
    ("Vites geçişleri hissedilmiyor bile.", "positive"),
    ("Trafik işareti tanıma sistemi çok doğru çalışıyor.", "positive"),
    ("Direksiyon simidi çok kaliteli hissettiriyor.", "positive"),
    ("Araç içindeki ses yalıtımı mükemmel.", "positive"),
    ("Tüm beklentilerimi karşıladı.", "positive"),
    ("Kesinlikle tavsiye ederim.", "positive"),
    ("Satın aldığıma hiç pişman değilim.", "positive"),
    ("Tek kelimeyle harika bir araç.", "positive"),
    ("Aracın süspansiyon sistemi tüm çukurları başarıyla absorbe ediyor.", "positive"),
    ("Direksiyon tepkileri oldukça hızlı ve net.", "positive"),
    ("Isıtmalı koltuklar kışın çok işe yarıyor.", "positive"),
    ("Arka koltuklar da ön koltuklar kadar rahat.", "positive"),
    ("Bagaj hacmi tam bir aile arabasına uygun.", "positive"),
    ("Araba yokuşlarda hiç zorlanmadan çıkıyor.", "positive"),
    ("Farlar gece sürüşü için oldukça yeterli.", "positive"),
    ("Aracın ivmelenmesi çok tatmin edici.", "positive"),
    ("Hız sabitleyici uzun yolda çok konforlu.", "positive"),
    ("Start-stop sistemi çok verimli çalışıyor.", "positive"),
    ("Yakıt tüketimi beklentimin çok altında.", "positive"),
    ("Dış tasarımı çok sportif görünüyor.", "positive"),
    ("İç mekânda kullanılan kumaş çok kaliteli.", "positive"),
    ("Android Auto özelliği çok kullanışlı.", "positive"),
    ("Araba şehir içi kullanım için ideal boyutta.", "positive"),
    ("Uzun yol performansı gerçekten etkileyici.", "positive"),
    ("Camlar sessizce açılıyor ve kapanıyor.", "positive"),
    ("Yokuş kalkış desteği çok işlevsel.", "positive"),
    ("Araç rüzgarı çok iyi kesiyor, sessiz içerisi.", "positive"),
    ("Yan aynalar görüş açısını çok iyi destekliyor.", "positive"),
    ("Otomatik vites geçişleri çok akıcı.", "positive"),
    ("Kornası bile kaliteli bir ses çıkarıyor.", "positive"),
    ("Aracın içi geniş ve ferah hissettiriyor.", "positive"),
    ("Araba güneşli havalarda bile serin kalıyor.", "positive"),
    ("Koltuk pozisyonları ayarlamak çok kolay.", "positive"),
    ("USB girişleri yeterli ve ulaşılabilir.", "positive"),
    ("Çocuk koltuğu için uygun ISOFIX yerleri var.", "positive"),
    ("Fabrika çıkışı lastikler kaliteli markaydı.", "positive"),
    ("Silecekler yağmurda çok iyi performans veriyor.", "positive"),
    ("Sürüş pozisyonu oldukça ergonomik.", "positive"),
    ("Araç sessiz çalışıyor, motor sesi neredeyse yok.", "positive"),
    ("Fren tepkisi hızlı ve kontrollü.", "positive"),
    ("Gösterge paneli modern ve okunması kolay.", "positive"),
    ("Anahtarsız giriş büyük kolaylık sağlıyor.", "positive"),
    ("İç mekân renk kombinasyonu çok hoş.", "positive"),
    ("Torpido gözü oldukça geniş.", "positive"),
    ("Arka park sensörleri çok işe yarıyor.", "positive"),
    ("Aracın yerden yüksekliği çok ideal.", "positive"),
    ("Dış aydınlatma estetik ve güçlü.", "positive"),
    ("Araba yeni gibi kokuyor, ferah.", "positive"),
    ("Yağ değişimi uyarısı zamanında geldi.", "positive"),
    ("Servisteki çalışanlar çok kibardı.", "positive"),
    ("Kasa yapısı sağlamlık hissi veriyor.", "positive"),
    ("Koltuk arkası cepler çok kullanışlı.", "positive"),
    ("Sunroof geniş ve havadar bir his katıyor.", "positive"),
    ("Motor ısınmadan çok hızlı çalışıyor.", "positive"),
    ("Vites geçişleri neredeyse hissedilmiyor.", "positive"),
    ("Kapıların kapanışı sağlamlık hissi veriyor.", "positive"),
    ("Tekerlek sesi içeride çok az duyuluyor.", "positive"),
    ("Uzun farlar mükemmel aydınlatma sağlıyor.", "positive"),
    ("Bluetooth bağlantısı saniyeler içinde yapılıyor.", "positive"),
    ("Yokuş iniş desteği güven veriyor.", "positive"),
    ("Araba güneş enerjili şarj sistemiyle geldi.", "positive"),
    ("Koltuk minderleri yumuşak ama destekleyici.", "positive"),
    ("Aracın garantisi beklentimin üstünde.", "positive"),
    ("Vites topuzu çok ergonomik tasarlanmış.", "positive"),
    ("Arabanın içindeki plastik kalitesi çok iyi.", "positive"),
    ("Direksiyon üzerindeki tuşlar kolay erişilebilir.", "positive"),
    ("Göğüs paneli kaliteli malzemeden yapılmış.", "positive"),
    ("Aydınlatma ambiyansı çok şık duruyor.", "positive"),
    ("Navigasyon güncel haritaları destekliyor.", "positive"),
    ("Araba tam zamanında teslim edildi.", "positive"),
    ("Şirket aracı olarak çok uygun bulduk.", "positive"),
    ("Küçük alanlarda manevra kabiliyeti çok iyi.", "positive"),
    ("Kör nokta uyarı sistemi çok başarılı.", "positive"),
    ("Direksiyon ısıtması kış aylarında harika.", "positive"),
    ("Ön cam buğu çözücü hemen çalışıyor.", "positive"),
    ("Araba kendini çok kaliteli hissettiriyor.", "positive"),
    ("Cihaz şarjı için USB-C çıkışı da var.", "positive"),
    ("Araba sürüşte güven hissi veriyor.", "positive"),
    ("Aile için ideal bir araç.", "positive"),
    ("Kilit sistemi hızlı ve güvenli.", "positive"),
    ("Cam tavan içeri çok ışık alıyor.", "positive"),
    ("Araba içi sessizliği mükemmel.", "positive"),
    ("Mobil uygulama ile uzaktan kontrol harika.", "positive"),
    ("Koltuk destekleri bel ağrısını azaltıyor.", "positive"),
    ("Kapı tutacakları çok ergonomik.", "positive"),
    ("Kabin içi aydınlatma otomatik ayarlanıyor.", "positive"),
    ("Yakıt dolum kapağı pratik açılıyor.", "positive"),
    ("Aracın dış boyası çok kaliteli görünüyor.", "positive"),
    ("Telefon tutucu alanı çok kullanışlı.", "positive"),
    ("Yokuşta kalkarken hiç geri kaymadı.", "positive"),
    ("Sürüş asistanı virajları başarılı alıyor.", "positive"),
    ("Lastik basınç sensörü uyarı verdiğinde işe yaradı.", "positive"),
    ("Arabanın amortisörleri yumuşak sürüş sağlıyor.", "positive"),
    ("Gözlük koyma yeri çok iyi düşünülmüş.", "positive"),
    ("Camlar tam kararında koyulukta.", "positive"),
    ("Tavan döşemesi kaliteli kumaştan yapılmış.", "positive"),
    ("Araç anahtarı çok şık tasarlanmış.", "positive"),
    ("Kış lastikleriyle teslim aldım, harika!", "positive"),
    ("Aracın bakımı kolay yapılıyor.", "positive"),
    ("Direksiyon sertliği ayarlanabiliyor.", "positive"),
    ("Tüm fonksiyonlar kolay öğreniliyor.", "positive"),
    ("Yol bilgisayarı çok detaylı veri veriyor.", "positive"),
    ("Araçta hiçbir yazılım hatası yaşamadım.", "positive"),
    ("Park asistanı dar alanlarda çok iş görüyor.", "positive"),
    ("Hız göstergesi dijital ve net.", "positive"),
    ("Yan camlar otomatik kapanıyor.", "positive"),
    ("Araç beklediğimden çok daha güçlü çıktı.", "positive"),
    ("Uzun yolculuklarda sırtım ağrımıyor.", "positive"),
    ("Araçtan indikten sonra ışıklar kendiliğinden kapanıyor.", "positive"),
    ("Yakıt tüketimi şehir dışı çok düşük.", "positive"),
    ("İç mekân temizliği kolay yapılıyor.", "positive"),
    ("Araç içi buzdolabı çok pratik.", "positive"),
    ("İnternet bağlantısı ile güncellenebilir sistem.", "positive"),
    ("Araba ilk çalıştırmada sessizce açılıyor.", "positive"),
    ("Aracın performansı şehir içi ve uzun yolda harika.", "positive"),
    ("Bluetooth bağlantısı saniyeler içinde kuruldu.", "positive"),
    ("Multimedya sistemi çok hızlı çalışıyor.", "positive"),
    ("Klima sisteminin sessizliği mükemmel.", "positive"),
    ("Navigasyon sistemi oldukça hassas ve güncel.", "positive"),
    ("Aracın iç mekânı ferah ve havadar.", "positive"),
    ("Yol tutuşu virajlarda da güven veriyor.", "positive"),
    ("Arka camların otomatik karartılması çok işe yarıyor.", "positive"),
    ("Fren sistemi çok dengeli çalışıyor.", "positive"),
    ("Farlar gece görüşünü adeta gündüze çeviriyor.", "positive"),
    ("Yalıtım o kadar iyi ki dışarıdan ses neredeyse gelmiyor.", "positive"),
    ("Koltukların sırt desteği uzun yol için ideal.", "positive"),
    ("Şarj portları her koltukta bulunuyor, çok pratik.", "positive"),
    ("Araba içi aydınlatmalar göz yormuyor.", "positive"),
    ("Lastikler teslim edildiğinde yepyeniydi.", "positive"),
    ("Test sürüşünde gösterdiği performansa hayran kaldım.", "positive"),
    ("İç tasarımı hem modern hem de sade.", "positive"),
    ("Motor çalıştırma sesi çok tatlı ve yumuşak.", "positive"),
    ("Otomatik park sistemi tek kelimeyle harika.", "positive"),
    ("Arabanın rengi güneşte parlıyor, çok estetik.", "positive"),
    ("Araba ilk bakışta kalite hissini veriyor.", "positive"),
    ("Havalandırma sisteminin kontrolü çok kolay.", "positive"),
    ("İçerideki malzeme kalitesi premium seviyede.", "positive"),
    ("Koltuk ısıtma özelliği soğuk havalarda vazgeçilmez.", "positive"),
    ("Cam tavan açıldığında içerisi ışık doluyor.", "positive"),
    ("Motor sesi dışarıda var ama içeride yok denecek kadar az.", "positive"),
    ("Frenler ani duruşlarda bile sarsıntısız.", "positive"),
    ("Yol bilgisayarı verileri çok detaylı ve faydalı.", "positive"),
    ("Akıllı telefon entegrasyonu kusursuz.", "positive"),
    ("Telefon kablosuz olarak hemen şarj oluyor.", "positive"),
    ("Çocuk koltuğu için yerleştirme çok kolay.", "positive"),
    ("Hızlı çalışmasıyla dikkat çekiyor.", "positive"),
    ("Dijital ekranlar yüksek çözünürlüklü ve net.", "positive"),
    ("Sürüş modları arasındaki geçişler pürüzsüz.", "positive"),
    ("Kapı açma-kapama sesi bile kalite hissi veriyor.", "positive"),
    ("Görüş açısı çok geniş, kör nokta problemi yok.", "positive"),
    ("Ayarlanabilir süspansiyon sürüşü kişiselleştiriyor.", "positive"),
    ("Bagaj bölmesi çok fonksiyonel.", "positive"),
    ("Yan camlardaki UV filtresi çok işe yarıyor.", "positive"),
    ("İç aydınlatmalar otomatik yanıyor, harika detay.", "positive"),
    ("Araçla ilk temas anından itibaren güven veriyor.", "positive"),
    ("Koltuklar uzun süreli kullanımda bile rahat.", "positive"),
    ("Servis randevusu almak çok kolaydı.", "positive"),
    ("Otomatik aynalar park sırasında kendiliğinden kapanıyor.", "positive"),
    ("Kısa farlar bile yeterli ışık sağlıyor.", "positive"),
    ("Uzaktan kumanda ile camları açmak çok pratik.", "positive"),
    ("Şerit takip sistemi çok hassas çalışıyor.", "positive"),
    ("Kısa süreli testte bile farkını hissettirdi.", "positive"),
    ("Araba içi uygulama güncellemeleri otomatik yapılıyor.", "positive"),
    ("Frenler sessiz ve etkili.", "positive"),
    ("Vites topuzu çok şık ve kaliteli.", "positive"),
    ("Telefon yansıtma özelliği sorunsuz çalışıyor.", "positive"),
    ("Direksiyon tutuşu eldiven gibi oturuyor.", "positive"),
    ("Otomatik ayna ayarı çok işlevsel.", "positive"),
    ("Koltuklar tamamen geriye yatırılabiliyor, mükemmel!", "positive"),
    ("Navigasyonun sesli komut sistemi çok başarılı.", "positive"),
    ("Aracın kaporta kalitesi yüksek seviyede.", "positive"),
    ("Aracın içi dışı kadar güzel.", "positive"),
    ("Her detayında özenli üretim hissediliyor.", "positive"),
    ("Sürüş keyfi inanılmaz tatmin edici.", "positive"),
    ("Aynalar görüş açısına göre otomatik ayarlanıyor.", "positive"),
    ("Araç menzili uzun, sık yakıt doldurmuyorum.", "positive"),
    ("Kolçak yüksekliği çok rahat.", "positive"),
    ("Aracın ekranı yansıma yapmıyor, rahat okunuyor.", "positive"),
    ("Park asistanı her koşulda iş görüyor.", "positive"),
    ("Aracın yazılımı sezgisel ve kullanıcı dostu.", "positive"),
    ("Fren pedalı yumuşak ama etkili.", "positive"),
    ("Kabin havası temiz ve havadar kalıyor.", "positive"),
    ("İç detaylar sade ama şık.", "positive"),
    ("Aracın içi dış seslerden yalıtılmış gibi.", "positive"),
    ("Soğutmalı koltuklar yaz için mükemmel.", "positive"),
    ("Araba çalışırken hiç sarsıntı olmuyor.", "positive"),
    ("Bagaj kapağı otomatik açılıyor, çok kolay.", "positive"),
    ("USB-C girişleri de mevcut, çok güncel.", "positive"),
    ("Yan koruma çıtaları çiziklerden koruyor.", "positive"),
    ("Ses sistemi hem net hem güçlü.", "positive"),
    ("Aracın dijital gösterge ekranı çok fonksiyonel.", "positive"),
    ("Arabanın çizgileri çok modern.", "positive"),
    ("Fren lambaları LED ve çok parlak.", "positive"),
    ("Ön cam görüş açısı çok geniş.", "positive"),
    ("Silecekler yağmur sensörüyle otomatik çalışıyor.", "positive"),
    ("Kapılar yumuşak kapanıyor, çarpmaya gerek kalmıyor.", "positive"),
    ("Yan camlar buğulanmadan açılıyor.", "positive"),
    ("Aracın iç rengi çok iç açıcı.", "positive"),
    ("Araçta koku filtresi olması büyük avantaj.", "positive"),
    ("Motor ısısı çok çabuk ideal seviyeye geliyor.", "positive"),
    ("Yüksek hızda bile direksiyon çok stabil.", "positive"),
    ("Araç içi bluetooth hoparlörler çok kaliteli.", "positive"),
    ("Otomatik ışık ayarı harika çalışıyor.", "positive"),
    ("Koltuk başlıkları ayarlanabilir ve rahat.", "positive"),
    ("İnce detaylara dikkat edilmiş bir araç.", "positive"),
    ("Sürüş modu değiştikçe araç davranışı değişiyor.", "positive"),
    ("Sistem güncellemeleri aracın performansını artırıyor.", "positive"),
    ("Test sürüşünden sonra hemen satın aldım.", "positive"),
    ("Tavsiye üzerine aldım, çok memnun kaldım.", "positive"),
    ("Servisten zamanında bilgi almak çok güzeldi.", "positive"),
    ("Yol tutuşu beni şaşırttı, çok başarılı.", "positive"),
    ("Eşya gözü çok fazla, her yer kullanışlı.", "positive"),
    ("Araç teslimatı tam zamanında gerçekleşti.", "positive"),
    ("Klimanın kokusu bile temiz.", "positive"),
    ("Yeni nesil tasarımı çok beğeniyorum.", "positive"),
    ("Satış danışmanı çok ilgiliydi, süreci kolaylaştırdı.", "positive"),
    ("Araç ilk kullanımda güven hissi veriyor.", "positive"),
    ("Araç üst segment hissi yaratıyor.", "positive"),
    ("Malzeme kalitesi fiyatına göre çok iyi.", "positive"),
    ("Servis çok yavaş, saatlerce bekledim.", "negative"),
    ("Araç içi plastik kalitesi çok düşük.", "negative"),
    ("Satış temsilcisi ilgisizdi.", "negative"),
    ("Araba sürekli arıza çıkarıyor.", "negative"),
    ("Koltuklar sert ve rahatsız.", "negative"),
    ("Navigasyon sistemi sürekli donuyor.", "negative"),
    ("Frenler güven vermiyor.", "negative"),
    ("Müşteri hizmetleri sorunumu çözmedi.", "negative"),
    ("Bluetooth bağlantısı sürekli kopuyor.", "negative"),
    ("Garanti kapsamı çok sınırlı.", "negative"),
    ("Serviste yanlış parça takıldı.", "negative"),
    ("İçeriye çok ses alıyor.", "negative"),
    ("Araç beklediğimden fazla yakıyor.", "negative"),
    ("Yedek parça temini haftalar sürdü.", "negative"),
    ("Fiyatına göre performansı düşük.", "negative"),
    ("Motor sesi fazla geliyor.", "negative"),
    ("İlk haftadan sorun yaşamaya başladım.", "negative"),
    ("Bayide kimse ilgilenmedi.", "negative"),
    ("Araçta boya hataları vardı.", "negative"),
    ("Klima çalışmıyor.", "negative"),
    ("Test sürüşü yapmamı bile istemediler.", "negative"),
    ("Yetkili servis çok pahalı.", "negative"),
    ("Araç virajlarda çok savruluyor.", "negative"),
    ("Farlar yetersiz aydınlatıyor.", "negative"),
    ("Araç içi aydınlatma çok zayıf.", "negative"),
    ("Donanım eksikleri var.", "negative"),
    ("Gösterge paneli hatalı bilgi veriyor.", "negative"),
    ("Kullanım kılavuzu yetersiz.", "negative"),
    ("Yakıt tüketimi belirtilenden fazla.", "negative"),
    ("Serviste kötü muamele gördüm.", "negative"),
    ("Araç soğuk havada zor çalışıyor.", "negative"),
    ("Renk seçeneği çok sınırlıydı.", "negative"),
    ("Bagaj kapağı zor kapanıyor.", "negative"),
    ("Süspansiyon sistemi çok sert.", "negative"),
    ("Şanzıman geçişleri hissediliyor.", "negative"),
    ("İç mekân dar, rahat değil.", "negative"),
    ("Torpido gözü çok küçük.", "negative"),
    ("Araç park ederken zorlanıyor.", "negative"),
    ("Park sensörleri geç tepki veriyor.", "negative"),
    ("Servis randevusu almak çok zor.", "negative"),
    ("Servis çalışanları kaba davrandı.", "negative"),
    ("Direksiyon çok sert.", "negative"),
    ("Silecekler düzgün çalışmıyor.", "negative"),
    ("Aracın içine su alıyor.", "negative"),
    ("Tavan döşemesi kısa sürede sarktı.", "negative"),
    ("Motor performansı yetersiz.", "negative"),
    ("Araçta koku problemi var.", "negative"),
    ("Lastik basınç göstergesi arızalı.", "negative"),
    ("Yakıt göstergesi doğru çalışmıyor.", "negative"),
    ("Koltuk ısıtma sistemi çalışmıyor.", "negative"),
    ("Servis çözüm üretmiyor.", "negative"),
    ("Kapılar zor kapanıyor.", "negative"),
    ("Şarj prizi çalışmıyor.", "negative"),
    ("Fren sesi rahatsız edici.", "negative"),
    ("Araba rampada zorlanıyor.", "negative"),
    ("Kabin içinde çok titreşim oluyor.", "negative"),
    ("Servis yedek parça için fahiş fiyat istedi.", "negative"),
    ("Müzik sistemi bozuk çıktı.", "negative"),
    ("Klimadan kötü koku geliyor.", "negative"),
    ("Araç sürekli sağa çekiyor.", "negative"),
    ("İç döşeme kısa sürede deforme oldu.", "negative"),
    ("Cam açma düğmeleri takılıyor.", "negative"),
    ("Araçta açıklanamayan sesler var.", "negative"),
    ("Kamera sistemi arızalı.", "negative"),
    ("Direksiyon derisi soyulmaya başladı.", "negative"),
    ("Yol bilgisayarı hatalı bilgi veriyor.", "negative"),
    ("Kaput çok kolay ısınıyor.", "negative"),
    ("Rüzgar sesi çok fazla geliyor.", "negative"),
    ("Aracın boyası güneşte soldu.", "negative"),
    ("Sürüş sırasında dengesiz hissediliyor.", "negative"),
    ("Bagaj çok küçük.", "negative"),
    ("Sunroof sızdırıyor.", "negative"),
    ("Arka koltuk diz mesafesi çok dar.", "negative"),
    ("Teyp sürekli resetleniyor.", "negative"),
    ("Araçta üretim hatası çıktı.", "negative"),
    ("Silecek suyu püskürtmüyor.", "negative"),
    ("Tekerlekler dengesiz dönüyor.", "negative"),
    ("Kapı kolları kısa sürede bozuldu.", "negative"),
    ("Yokuş kalkış desteği çalışmıyor.", "negative"),
    ("Vites topuzu gevşedi.", "negative"),
    ("Yan aynalar sabit durmuyor.", "negative"),
    ("Serviste ilgisiz davranıldı.", "negative"),
    ("İlk gün sorun yaşamam hoş olmadı.", "negative"),
    ("Havalandırma sesli çalışıyor.", "negative"),
    ("Şasi gıcırtı yapıyor.", "negative"),
    ("Koltuk arkaları çok ince.", "negative"),
    ("Kapılar kapanınca çok ses çıkarıyor.", "negative"),
    ("Direksiyon titreşiyor.", "negative"),
    ("Ön camda buğu sürekli oluşuyor.", "negative"),
    ("Araç dengesiz fren yapıyor.", "negative"),
    ("Koltuk ayarı düzgün çalışmıyor.", "negative"),
    ("Servis yanlış fatura çıkardı.", "negative"),
    ("İç mekân malzemesi ucuz duruyor.", "negative"),
    ("Donanım eksik geldi.", "negative"),
    ("Garanti kapsamı çok dar.", "negative"),
    ("Ses yalıtımı yok denecek kadar az.", "negative"),
    ("Fabrika çıkışlı hatalar vardı.", "negative"),
    ("Araçta boya kalıntıları kaldı.", "negative"),
    ("Servis söz verdiği tarihte aracı teslim etmedi.", "negative"),
    ("Yedek anahtar verilmedi.", "negative"),
    ("Araç tesliminde çizikler vardı.", "negative"),
    ("Test sürüşü imkânı sağlanmadı.", "negative"),
    ("Aracın teknik verileri eksik sunuldu.", "negative"),
    ("Koltuk kumaşı kalitesiz.", "negative"),
    ("Kargo geç geldi.", "negative"),
    ("Siparişimle teslim edilen araç farklıydı.", "negative"),
    ("Arka cam ısıtması çalışmıyor.", "negative"),
    ("Direksiyon ortalanmıyor.", "negative"),
    ("Sürekli arıza ışığı yanıyor.", "negative"),
    ("Sıfır aldığım araçta kaput çizikleri çıktı.", "negative"),
    ("Aracın motoru sürekli arıza veriyor.", "negative"),
    ("Yakıt tüketimi aşırı yüksek, hiç ekonomik değil.", "negative"),
    ("Koltuklar çok sert, uzun yolda rahatsız ediyor.", "negative"),
    ("İç mekânda plastik aksamlar kalitesiz duruyor.", "negative"),
    ("Servise ulaşmak çok zor, sürekli meşgul.", "negative"),
    ("Frenler aniden tutuyor, sürüşü tehlikeli hale getiriyor.", "negative"),
    ("Yokuşta kalkış desteği çalışmıyor.", "negative"),
    ("Navigasyon sürekli yanlış yönlendiriyor.", "negative"),
    ("Bluetooth bağlantısı sürekli kopuyor.", "negative"),
    ("Kliması yeterince soğutmuyor.", "negative"),
    ("Araçta rüzgar sesi çok geliyor.", "negative"),
    ("Vites geçişleri sert ve rahatsız edici.", "negative"),
    ("Yetkili bayi teslim süresini sürekli erteledi.", "negative"),
    ("Motor sesi içeride çok fazla duyuluyor.", "negative"),
    ("Bagaj kapağı zor kapanıyor.", "negative"),
    ("Yokuşta geri kayma problemi yaşıyorum.", "negative"),
    ("Servis randevusu almak haftalar sürüyor.", "negative"),
    ("Araç içi ekran donuyor ve tepki vermiyor.", "negative"),
    ("Ses sistemi bozuk teslim edildi.", "negative"),
    ("Araçta koku problemi var, geçmiyor.", "negative"),
    ("Yedek parça için bir ay beklemek zorunda kaldım.", "negative"),
    ("Satış sonrası hizmet yetersiz.", "negative"),
    ("Koltuk kumaşı çok dayanıksız.", "negative"),
    ("Dış tasarımı fotoğraftaki gibi değildi.", "negative"),
    ("Uzun yolda direksiyon titriyor.", "negative"),
    ("Süspansiyonlar çukurlarda sert tepki veriyor.", "negative"),
    ("Camlar buğulanıyor, çözüm bulunamıyor.", "negative"),
    ("Farlar gece yeterince aydınlatmıyor.", "negative"),
    ("Anahtar sistemi sürekli hata veriyor.", "negative"),
    ("Geri görüş kamerası geç açılıyor.", "negative"),
    ("Park sensörleri yanlış alarm veriyor.", "negative"),
    ("Radyosu bozuk çalışıyor.", "negative"),
    ("Araç durup dururken stop ediyor.", "negative"),
    ("Vites kolu yerinden çıkacak gibi duruyor.", "negative"),
    ("Egzozdan garip sesler geliyor.", "negative"),
    ("Boya kalitesi çok kötü, hemen çizildi.", "negative"),
    ("Araç lastikleri fabrikadan bozuk çıktı.", "negative"),
    ("Fatura hatalı kesilmişti.", "negative"),
    ("Yetkili servis garanti kapsamını yanlış uyguladı.", "negative"),
    ("Tavanda su sızıntısı oluştu.", "negative"),
    ("Araç içi ışıklandırma çok zayıf.", "negative"),
    ("Kilit sistemi güven vermiyor.", "negative"),
    ("Servis çalışanları ilgisizdi.", "negative"),
    ("Benzin göstergesi arızalı çalışıyor.", "negative"),
    ("Bagaj hacmi beklediğimden çok daha küçük.", "negative"),
    ("İnternette yazan özelliklerin bazıları yoktu.", "negative"),
    ("Far ayarı fabrika çıkışı hatalıydı.", "negative"),
    ("Direksiyon simidi soyulmaya başladı.", "negative"),
    ("Araç içinde sürekli bir tıkırtı sesi geliyor.", "negative"),
    ("Kapılar zor açılıyor, çok sert.", "negative"),
    ("İç aydınlatma lambaları çalışmıyor.", "negative"),
    ("Aracın boyası birkaç haftada soldu.", "negative"),
    ("Kol dayama yerleri çok rahatsız.", "negative"),
    ("Test sürüşü sırasında araç arıza verdi.", "negative"),
    ("İç mekân çok dar ve basık.", "negative"),
    ("Panoramik cam tavan su akıtıyor.", "negative"),
    ("Yakıt göstergesi doğru çalışmıyor.", "negative"),
    ("Fiyat performans açısından sınıfta kaldı.", "negative"),
    ("USB girişi çalışmıyor.", "negative"),
    ("Servis fiyatları fahiş.", "negative"),
    ("Kaput altından sürekli ses geliyor.", "negative"),
    ("Koltuk ayarı kolay bozuluyor.", "negative"),
    ("Yazılım güncellemesi ile sistem bozuldu.", "negative"),
    ("Koltuk ısıtması hiç çalışmadı.", "negative"),
    ("Cam tavanın açma tuşu takılıyor.", "negative"),
    ("Anahtarsız giriş sisteminde sıkıntı var.", "negative"),
    ("Silecekler camı temizlemiyor.", "negative"),
    ("Araç içi ekranı çok yavaş.", "negative"),
    ("Emniyet kemeri çok sert geri dönüyor.", "negative"),
    ("Kapılar yolculuk sırasında açılma uyarısı veriyor.", "negative"),
    ("Gösterge paneli titriyor.", "negative"),
    ("Klimanın yönlendirmesi çalışmıyor.", "negative"),
    ("Satıcı fiyat konusunda yanıltıcı bilgi verdi.", "negative"),
    ("Araç içi telefon bağlantısı kesiliyor.", "negative"),
    ("Fren balataları erkenden bitti.", "negative"),
    ("Rölantide sarsıntı yapıyor.", "negative"),
    ("Tavan döşemesi zamanla sarktı.", "negative"),
    ("Multimedya ekranı kararıyor.", "negative"),
    ("Kapı fitilleri yerinden çıkıyor.", "negative"),
    ("Test sürüşü yapmadan satmaya çalıştılar.", "negative"),
    ("Koltuk başlıkları konforsuz.", "negative"),
    ("Araç içi ses izolasyonu çok kötü.", "negative"),
    ("Farlar sürekli buğulanıyor.", "negative"),
    ("Servis bana dönüş yapmadı.", "negative"),
    ("Rüzgar sesi aşırı rahatsız edici.", "negative"),
    ("Araç teslimi çok geç yapıldı.", "negative"),
    ("Vites geçişlerinde ses geliyor.", "negative"),
    ("Tekerleklerden dengesiz ses geliyor.", "negative"),
    ("Dikiz aynası kendi kendine oynuyor.", "negative"),
    ("Hava yastığı uyarısı sürekli yanıyor.", "negative"),
    ("Torpido gözü zor kapanıyor.", "negative"),
    ("İç mekan aydınlatması titrek çalışıyor.", "negative"),
    ("Satış sürecinde söz verilip yapılmayan şeyler oldu.", "negative"),
    ("Aracın sesi dışarıdan çok fazla geliyor.", "negative"),
    ("Fabrika çıkışı lastik balanssızdı.", "negative"),
    ("Gösterge ekranı donuyor.", "negative"),
    ("Yol tutuşu zayıf, virajlarda güvensiz.", "negative"),
    ("Arka koltuklar çok dar.", "negative"),
    ("Güneşlik çok küçük ve işlevsiz.", "negative"),
    ("Yokuş yukarı çıkarken zorlanıyor.", "negative"),
    ("Şanzıman sorunu nedeniyle iade etmek zorunda kaldım.", "negative"),
    ("Kapı sensörleri çalışmıyor.", "negative"),
    ("Araç sürekli arıza ışığı yakıyor.", "negative"),
    ("Multimedya sistemi güncellemeden sonra çalışmıyor.", "negative"),
    ("Yakıt tüketimi fabrika verilerinin çok üzerinde.", "negative"),
    ("Koltuk sırt ayarı bozuktu, değiştirmek zorunda kaldım.", "negative"),
    ("Kapı gıcırtısı giderilemedi.", "negative"),
    ("Torpido kapağı yerinden çıktı.", "negative"),
    ("Silecek motoru çalışmıyor.", "negative"),
    ("İlk haftada boya atması yaşandı.", "negative"),
    ("Araç çakmaklığı çalışmıyor.", "negative"),
    ("Yokuş kalkış desteği devreye girmiyor.", "negative"),
    ("Araçta navigasyon Türkçe desteklemiyor.", "negative"),
    ("Servis çalışanı ilgisiz ve kaba davrandı.", "negative"),
    ("Arabanın içi sürekli buğulanıyor.", "negative"),
    ("Dikiz aynası sabit durmuyor.", "negative"),
    ("Kapı içi döşemesi kalktı.", "negative"),
    ("Araç gaz yemiyor, hızlanmakta zorlanıyor.", "negative"),
    ("İç mekânda boya kokusu geçmedi.", "negative"),
    ("Lastik sensörleri sürekli hata veriyor.", "negative"),
    ("Ön camda üretim hatası vardı.", "negative"),
    ("Göstergede arıza ışığı sabit yanıyor.", "negative"),
    ("Direksiyon dönerken sürtme sesi geliyor.", "negative"),
    ("Arka cam rezistansı çalışmıyor.", "negative"),
    ("İç mekan çok sesli.", "negative"),
    ("Emniyet kemeri kilitlenmiyor.", "negative"),
    ("Motor hararet yapıyor.", "negative"),
    ("Anahtar pili çok çabuk bitiyor.", "negative"),
    ("Araç içi sıcaklık ayarı dengesiz.", "negative"),
    ("Test sürüşünde söz verdikleri kampanya geçerli olmadı.", "negative"),
    ("Direksiyon çok ağır.", "negative"),
    ("Yağmur sensörü yanlış çalışıyor.", "negative"),
    ("Arka cam su jeti bozuk.", "negative"),
    ("Yakıt deposu kapağı kapanmıyor.", "negative"),
    ("Donanım listesi ile gelen özellikler uyuşmuyor.", "negative"),
    ("Araçta sürekli bir yanık kokusu var.", "negative"),
    ("Servis bakım ücretleri abartılı.", "negative"),
    ("Far ayarı kendiliğinden değişiyor.", "negative"),
    ("Bluetooth ses aktarmıyor.", "negative"),
    ("Koltuk ayar kolları kırıldı.", "negative"),
    ("Panoramik camdan su sızdı.", "negative"),
    ("Kilit sistemi tek tuşla açılmıyor.", "negative"),
    ("Klimanın gazı bitmişti.", "negative"),
    ("Ön camdan ses geliyor.", "negative"),
    ("Kapı fitili içeriye su alıyor.", "negative"),
    ("Bagaj zemininde gevşeklik var.", "negative"),
    ("Cam tavan gıcırdıyor.", "negative"),
    ("Araç çalışırken titreşim yapıyor.", "negative"),
    ("Radyatör fanı sesli çalışıyor.", "negative"),
    ("Direksiyon ısınmıyor, soğukta kullanışsız.", "negative"),
    ("Telefon yansıtma özelliği hiç çalışmadı.", "negative"),
    ("Torpido içi ışık yanmıyor.", "negative"),
    ("Süspansiyon çok sert, çukurları direkt hissettiriyor.", "negative"),
    ("Kapıdan içeriye toz giriyor.", "negative"),
    ("Multimedya sisteminde donmalar oluyor.", "negative"),
    ("Koltuğun yayları ses çıkarıyor.", "negative"),
    ("Motor geç çalışıyor.", "negative"),
    ("Hız sabitleyici çalışmadı.", "negative"),
    ("Araç kapalı alanda bile sinyal çekmiyor.", "negative"),
    ("Tavan lambası yanıp sönüyor.", "negative"),
    ("İçerideki plastik kokusu geçmedi.", "negative"),
    ("Servis parça değişimi yapmamış olmasına rağmen ücret aldı.", "negative"),
    ("Gün ışığında ekran görünmüyor.", "negative"),
    ("Bagaj açma düğmesi çalışmıyor.", "negative"),
    ("Silecekler camı çiziyor.", "negative"),
    ("USB üzerinden müzik oynatmıyor.", "negative"),
    ("Araç ses sistemi cızırtılı.", "negative"),
    ("Koltuk arkası file yırtık geldi.", "negative"),
    ("Araç soğukken çalışmıyor.", "negative"),
    ("Camlar içeriden buharlanıyor.", "negative"),
    ("Gösterge paneli zaman zaman kapanıyor.", "negative"),
    ("Acil fren destek sistemi devreye girmiyor.", "negative"),
    ("Satış sonrası destek sıfır.", "negative"),
    ("Güneşlik aynası yerinden çıktı.", "negative"),
    ("Kör nokta uyarı sistemi çalışmıyor.", "negative"),
    ("Araç geri viteste ses çıkarıyor.", "negative"),
    ("Kapılar sert ve zor kapanıyor.", "negative"),
    ("Direksiyon düz durmuyor.", "negative"),
    ("Yedek lastik eksikti.", "negative"),
    ("Çakmak soketi boş geldi.", "negative"),
    ("Araç içi LED aydınlatmalar çalışmıyor.", "negative"),
    ("Yakıt deposu kapağı gevşek.", "negative"),
    ("Kapı kolları kalitesiz malzemeden yapılmış.", "negative"),
    ("Klima fanı sesli çalışıyor.", "negative"),
    ("Elektrik sistemi arıza veriyor.", "negative"),
    ("Ön camda çatlak oluştu.", "negative"),
    ("Vites göstergesi geç değişiyor.", "negative"),
    ("Navigasyon açılmıyor.", "negative"),
    ("Cam açma düğmesi bozuldu.", "negative"),
    ("Farlar titriyor.", "negative"),
    ("Kaput açık uyarısı hatalı geliyor.", "negative"),
    ("Motor yağı çabuk eksiliyor.", "negative"),
    ("Bagaj kapanmıyor.", "negative"),
    ("Arka cam motoru arızalı.", "negative"),
    ("Acil durum freni aşırı sert.", "negative"),
    ("Koltuk ısıtması dengesiz çalışıyor.", "negative"),
    ("İç dikiz aynası sabit durmuyor.", "negative"),
    ("El freni çok sert çekiliyor.", "negative"),
    ("Anahtar arabayı algılamıyor.", "negative"),
    ("Motor çalışırken sarsıntı yapıyor.", "negative"),
    ("Açılır tavan takılıyor.", "negative"),
    ("Araçta yer alan USB çıkışları bozuk.", "negative"),
    ("Arka koltuklar konforsuz.", "negative"),
    ("Donanıma göre fiyatı çok pahalı.", "negative"),
    ("Eğimli yolda geri kayıyor.", "negative"),
    ("Satış sonrası ilgisizlik büyük hayal kırıklığı.", "negative"),
    ("Aracı detaylıca inceledim.", "neutral"),
    ("Bugün bayiye uğradım, kalabalıktı.", "neutral"),
    ("Servise gitmeden önce randevu aldım.", "neutral"),
    ("Lastik basıncını kontrol ettim.", "neutral"),
    ("Kataloğu internetten inceledim.", "neutral"),
    ("Arabayı test etmek istiyorum.", "neutral"),
    ("Araçla ilgili bilgi aldım.", "neutral"),
    ("Bakım zamanı geldiğini fark ettim.", "neutral"),
    ("Görsel olarak güzel ama karar veremedim.", "neutral"),
    ("Satış danışmanıyla görüştüm.", "neutral"),
    ("Fiyat listesi güncellendi.", "neutral"),
    ("Yedek anahtarımı servisten aldım.", "neutral"),
    ("Araç temizdi, kullanıma hazırdı.", "neutral"),
    ("Renk seçeneklerini karşılaştırdım.", "neutral"),
    ("Araba hakkında yorum yapmadım.", "neutral"),
    ("Model karşılaştırması yaptım.", "neutral"),
    ("Satış ofisi sabah açılıyor.", "neutral"),
    ("Yeni modeller gelmiş.", "neutral"),
    ("İç hacmi geniş gibi duruyor.", "neutral"),
    ("Teknik özellikleri dikkatimi çekti.", "neutral"),
    ("Bagaj hacmini ölçtüm.", "neutral"),
    ("Donanım seviyesi orta düzeyde.", "neutral"),
    ("Sürüş sırasında müzik dinledim.", "neutral"),
    ("Havalandırma çalışıyor gibi.", "neutral"),
    ("Görünüşü sade ama şık.", "neutral"),
    ("Koltuklar deri değilmiş.", "neutral"),
    ("Opsiyonel donanımlar pahalı geldi.", "neutral"),
    ("Kampanya var mı diye sordum.", "neutral"),
    ("Katalogdaki bilgiler yeterliydi.", "neutral"),
    ("Test sürüşü için tarih aldım.", "neutral"),
    ("Daha önce bu modeli kullanmadım.", "neutral"),
    ("Kiralık olarak da sunuluyor.", "neutral"),
    ("Araba yeni yıkanmıştı.", "neutral"),
    ("İç mekan oldukça temizdi.", "neutral"),
    ("Satıcı bilgi verdi, karar vermedim.", "neutral"),
    ("Görüntüsü hoş ama emin değilim.", "neutral"),
    ("Yakıt tüketimi ortalama gibi.", "neutral"),
    ("Ses sistemi çalışıyor.", "neutral"),
    ("Park sensörleri mevcutmuş.", "neutral"),
    ("Bagaj kapağı otomatik değilmiş.", "neutral"),
    ("Araç teslim süresi 2 hafta dediler.", "neutral"),
    ("Dosyaları teslim ettim.", "neutral"),
    ("Ekspertiz raporunu inceledim.", "neutral"),
    ("Koltuklar yeterince genişti.", "neutral"),
    ("İç mekanda ekran biraz küçüktü.", "neutral"),
    ("Kullanıcı el kitabını okudum.", "neutral"),
    ("Sadece camlar filmli değilmiş.", "neutral"),
    ("Yeni jant tasarımı dikkat çekiciydi.", "neutral"),
    ("Navigasyon sistemi güncelmiş.", "neutral"),
    ("Motor hacmi ortalama düzeydeymiş.", "neutral"),
    ("Kiralama opsiyonlarını değerlendirdim.", "neutral"),
    ("Kredili alım seçeneklerine baktım.", "neutral"),
    ("Araç garantisi 3 yılmış.", "neutral"),
    ("Daha önce aynı modeli bir arkadaşım aldı.", "neutral"),
    ("Dış tasarımı fena değilmiş.", "neutral"),
    ("Klimanın ayarını kontrol ettim.", "neutral"),
    ("Aracı inceleyip karar vereceğim.", "neutral"),
    ("Biraz daha düşüneyim dedim.", "neutral"),
    ("Bagaj halısı oldukça kaliteliydi.", "neutral"),
    ("Cam tavan biraz daha pahalıymış.", "neutral"),
    ("Standart donanım listesi verildi.", "neutral"),
    ("Araçla ilgili bilgi verildi ama karar vermedim.", "neutral"),
    ("Sunroof seçeneği opsiyonelmiş.", "neutral"),
    ("Araç yolda sessizdi ama emin olamadım.", "neutral"),
    ("Far tasarımı ilginçti.", "neutral"),
    ("Bir hafta sonra tekrar bakacağım.", "neutral"),
    ("Arka koltuklar katlanabiliyor.", "neutral"),
    ("Araçta geri görüş kamerası varmış.", "neutral"),
    ("Fren sistemi ABS destekliymiş.", "neutral"),
    ("Direksiyon hassasiyeti dikkatimi çekti.", "neutral"),
    ("Serviste sıradaydım.", "neutral"),
    ("Kasko seçeneklerini değerlendirdim.", "neutral"),
    ("Yakıt deposu 50 litreymiş.", "neutral"),
    ("İnceleme sonunda yorum yapmadım.", "neutral"),
    ("Faturayı kontrol ettim.", "neutral"),
    ("Araç içi ışıklandırma farklıydı.", "neutral"),
    ("Güvenlik paketi dahilmiş.", "neutral"),
    ("Motor sesi çok belirgin değildi.", "neutral"),
    ("Bagaj açma düğmesi kolay ulaşılır.", "neutral"),
    ("Bluetooth bağlantısını denedim.", "neutral"),
    ("Dışarıdan sessiz çalışıyor.", "neutral"),
    ("Koltuk ayarları manuelmiş.", "neutral"),
    ("Aynalar elektrikliymiş.", "neutral"),
    ("Yokuş kalkış desteği var.", "neutral"),
    ("Donanım seviyeleri arasında fark var.", "neutral"),
    ("Test sürüşü 20 dakika sürdü.", "neutral"),
    ("Araba galeriye yeni gelmiş.", "neutral"),
    ("Kıyaslama yapmaya devam edeceğim.", "neutral"),
    ("Kullanan tanıdıklarım memnunmuş.", "neutral"),
    ("Yol bilgisayarı verimli çalışıyor gibi.", "neutral"),
    ("İç döşeme kumaşmış.", "neutral"),
    ("Bagaj kapağı ağırdı.", "neutral"),
    ("Dış renk griymiş.", "neutral"),
    ("Motor bilgisi broşürde yazıyordu.", "neutral"),
    ("Satış temsilcisi bilgi verdi.", "neutral"),
    ("Beklemeye alındım.", "neutral"),
    ("Aracı satın almadım, sadece inceledim.", "neutral"),
    ("Bayi yoğun olduğu için bekledim.", "neutral"),
    ("İnceleme sonrası servisle iletişime geçeceğim.", "neutral"),
    ("Araba hakkında notlar aldım.", "neutral"),
    ("Deneme sürüşüne katıldım.", "neutral"),
    ("Görseller web sitesinde mevcuttu.", "neutral"),
    ("Hangi donanımı alacağıma karar veremedim.", "neutral"),
    ("Arkadaşlarımın yorumlarını dinledim.", "neutral"),
    ("Araç tavanı mat değilmiş.", "neutral"),
    ("Motor yağı değişim zamanı gelmiş.", "neutral"),
    ("Araçta paspaslar standart geliyormuş.", "neutral"),
    ("Klimanın kumandası dokunmatikti.", "neutral"),
    ("Müzik sistemi bluetooth destekliyordu.", "neutral"),
    ("Araçta ön park sensörü yokmuş.", "neutral"),
    ("Hemen karar veremedim.", "neutral"),
    ("Koltukların rengi biraz açıkmış.", "neutral"),
    ("İç mekanda fazla eşya gözü yokmuş.", "neutral"),
    ("Navigasyon haritası güncel görünüyordu.", "neutral"),
    ("Arabayı detaylıca temizlemişlerdi.", "neutral"),
    ("Broşürdeki bilgilerle uyuşuyor.", "neutral"),
    ("Jantların boyutu standartmış.", "neutral"),
    ("Kapı kilitleri uzaktan çalışıyormuş.", "neutral"),
    ("Silecek suyu deposu doluydu.", "neutral"),
    ("İnceleme sonrası bir karar vermedim.", "neutral"),
    ("Arka camlar otomatikmiş.", "neutral"),
    ("Multimedya sistemi ekranı parlaktı.", "neutral"),
    ("Dış ayna sinyalleri dikkat çekiciydi.", "neutral"),
    ("Direksiyon kaplaması deriydi.", "neutral"),
    ("Bagaj ışığı loş geldi.", "neutral"),
    ("Gösterge paneli sade tasarlanmış.", "neutral"),
    ("Araba teslimatı bir hafta sürüyormuş.", "neutral"),
    ("Test sürüşü randevusu iptal oldu.", "neutral"),
    ("Park freni manuelmiş.", "neutral"),
    ("Kapı açma kolları metal değilmiş.", "neutral"),
    ("Koltuk ısıtma seçeneği opsiyonelmiş.", "neutral"),
    ("Araçta sunroof yokmuş.", "neutral"),
    ("Tavan rengi farklıymış.", "neutral"),
    ("Test sürüşü sonrası bilgi verilecekmiş.", "neutral"),
    ("Müzik sistemini denedim.", "neutral"),
    ("Araç bakım kitabı teslim edildi.", "neutral"),
    ("Kapı çıtaları dikkat çekmedi.", "neutral"),
    ("Yeni modelde arka cam daha küçükmüş.", "neutral"),
    ("Araç fiyatı henüz netleşmemiş.", "neutral"),
    ("Gösterge dijital değilmiş.", "neutral"),
    ("Arka koltuk kafalıkları ayarlanabilir.", "neutral"),
    ("Aydınlatma LED değilmiş.", "neutral"),
    ("Araçta çakmak soketi var.", "neutral"),
    ("Kaput açma kolu sol alttaymış.", "neutral"),
    ("Sürücü koltuğu yükseltilmişti.", "neutral"),
    ("İç mekan geniş ama alçak.", "neutral"),
    ("Tekerlekler biraz inceymiş.", "neutral"),
    ("Direksiyon üzerinde tuşlar var.", "neutral"),
    ("Geri görüş kamerası yukarı yerleştirilmiş.", "neutral"),
    ("Kapıların kapanışı sessizdi.", "neutral"),
    ("Gövde yüksekliği değişmemiş.", "neutral"),
    ("Silecekler camın köşesini temizlemiyordu.", "neutral"),
    ("Yeni modelde bazı değişiklikler olmuş.", "neutral"),
    ("Araç tavanı cam değilmiş.", "neutral"),
    ("Vites topuzu sade tasarlanmış.", "neutral"),
    ("Koltuk yan destekleri yokmuş.", "neutral"),
    ("Araba beklediğimden küçüktü.", "neutral"),
    ("Bayiye ulaşım kolaydı.", "neutral"),
    ("Arka koltuk mesafesi yeterliydi.", "neutral"),
    ("Yedek anahtar plastikti.", "neutral"),
    ("Farlar otomatik değilmiş.", "neutral"),
    ("Araçta hızlı şarj girişi yokmuş.", "neutral"),
    ("Jant tasarımı klasikmiş.", "neutral"),
    ("Motor hacmi düşük sınıftaymış.", "neutral"),
    ("Satın alma süreci açıklanmadı.", "neutral"),
    ("Dijital klima paneli çalışıyordu.", "neutral"),
    ("Kol dayama alanı dar gibi geldi.", "neutral"),
    ("Kapı cebi çok büyük değilmiş.", "neutral"),
    ("Torpido gözü aydınlatmalı değilmiş.", "neutral"),
    ("Arka koltuk eğimi sabitmiş.", "neutral"),
    ("Ekran yansıma yapıyordu.", "neutral"),
    ("Araç hakkında kısa bilgi verdiler.", "neutral"),
    ("Donanım paketleri hakkında bilgi aldım.", "neutral"),
    ("USB girişi çalışıyordu.", "neutral"),
    ("Ses yalıtımı çok iyi değilmiş.", "neutral"),
    ("Katalog fiyatlarıyla showroom fiyatı uyumlu değilmiş.", "neutral"),
    ("Araçta bagaj filesi yokmuş.", "neutral"),
    ("Camlar çift katlı değilmiş.", "neutral"),
    ("İç aydınlatma beyazdı.", "neutral"),
    ("Koltuğun kumaşı sert geldi.", "neutral"),
    ("Koltuk arkası cepler yokmuş.", "neutral"),
    ("Ayna ayarı manuelmiş.", "neutral"),
    ("Sürüş modları yokmuş.", "neutral"),
    ("Yakıt türü dizeldi.", "neutral"),
    ("Araç içi ambiyans aydınlatma eksikti.", "neutral"),
    ("Gösterge paneli gece aydınlatması açık değildi.", "neutral"),
    ("Araçta hız sabitleyici yoktu.", "neutral"),
    ("Güneşlikte ayna yokmuş.", "neutral"),
    ("Test sürüşü sırasında sessizdi.", "neutral"),
    ("Fiyatlar euro bazlıymış.", "neutral"),
    ("Araçta havalandırma menfezi azdı.", "neutral"),
    ("Motor sesi fazla gelmiyordu.", "neutral"),
    ("Geri viteste ses çıkıyordu.", "neutral"),
    ("Yol bilgisayarı detaylı değildi.", "neutral"),
    ("Sürüşte zorlanmadım.", "neutral"),
    ("Arka camlar daha dar yapılmış.", "neutral"),
    ("İç mekan biraz karanlıktı.", "neutral"),
    ("Jantlar çizilmişti.", "neutral"),
    ("Araba çiziksizdi.", "neutral"),
    ("Kapılar düzgün kapanıyordu.", "neutral"),
    ("Satış temsilcisi not aldı, dönüş yapacakmış.", "neutral"),
    ("Model seçeneklerini sundular.", "neutral"),
    ("Araçtan indikten sonra bilgi verdiler.", "neutral"),
    ("Direksiyon ayarını değiştirdim.", "neutral"),
    ("Çakmak soketi çalışıyordu.", "neutral"),
    ("Koltuk arkası masa yokmuş.", "neutral"),
    ("Kasa tipi hatchbackmiş.", "neutral"),
    ("İnceleme sonrası kampanya soruldu.", "neutral"),
    ("Araçta cam tavan seçeneği yokmuş.", "neutral"),
    ("Koltuk sırtı ayarlanamıyormuş.", "neutral"),
    ("El fren kolu yüksekmiş.", "neutral"),
    ("Arabanın altında plastik koruma varmış.", "neutral"),
    ("İnceleme sırasında not tuttum.", "neutral"),
    ("Teslimat süresi net değilmiş.", "neutral"),
    ("Kabin içi boş görünüyor.", "neutral"),
    ("Motor performansı hakkında yorum yapmadım.", "neutral"),
    ("Test sürüşü sırasında konuşulmadı.", "neutral"),
    ("Fiyat bilgisi sonradan verilecekmiş.", "neutral"),
    ("Kapı içi döşemesi farklıymış.", "neutral"),
    ("Aracın teknik verileri katalogda belirtilmişti.", "neutral"),
    ("Gövde tipi beklendiğim gibiydi.", "neutral"),
    ("Yetkili servis bilgileri broşürde vardı.", "neutral"),
    ("Direksiyon simidi klasik boyuttaydı.", "neutral"),
    ("Bagaj hacmi ortalama seviyedeydi.", "neutral"),
    ("Koltuk pozisyonu sabit kalmış.", "neutral"),
    ("Aracın rengi canlıydı ama tercih etmedim.", "neutral"),
    ("Cam tavan opsiyonel sunuluyormuş.", "neutral"),
    ("Sürüş pozisyonu ne alçak ne yüksek.", "neutral"),
    ("Kullanım kılavuzu detaylı hazırlanmıştı.", "neutral"),
    ("Yakıt deposu konumu alışıldık yerindeydi.", "neutral"),
    ("Kapi menteşeleri sessiz çalışıyordu.", "neutral"),
    ("Farlar halojenmiş, LED değilmiş.", "neutral"),
    ("Aydınlatma tuşları klasik konumdaydı.", "neutral"),
    ("Multimedya sistemi güncelleme istemiş.", "neutral"),
    ("Gövde rengi alternatifleri sınırlıydı.", "neutral"),
    ("Dış görünüşte dikkat çeken bir detay yoktu.", "neutral"),
    ("Yedek lastik konumlandırması bagaj altındaydı.", "neutral"),
    ("Servis randevusu iki gün sonrasına verildi.", "neutral"),
    ("Tavan yüksekliği beklediğim gibiydi.", "neutral"),
    ("Koltuk ayar düğmeleri yumuşak çalışıyordu.", "neutral"),
    ("Kasa çizgileri çok belirgin değildi.", "neutral"),
    ("Kapı kolu tasarımı sade kalmış.", "neutral"),
    ("Korna sesi standarttı.", "neutral"),
    ("Torpido iç hacmi fazla büyük değildi.", "neutral"),
    ("Anahtar kabı plastikti.", "neutral"),
    ("Silecekler camın köşesini zor temizliyordu.", "neutral"),
    ("Yokuş kalkış desteği yokmuş.", "neutral"),
    ("Fiyat bilgisini satış temsilcisi sonra gönderecekmiş.", "neutral"),
    ("Güneşlik aynası ışıklı değilmiş.", "neutral"),
    ("Havalandırma tuşları sert çalışıyordu.", "neutral"),
    ("Koltuklar kumaş kaplıymış.", "neutral"),
    ("Arka koltuklar düz sıralıymış.", "neutral"),
    ("Jant markası katalogda belirtilmemişti.", "neutral"),
    ("Satış temsilcisi araçla ilgili genel bilgi verdi.", "neutral"),
    ("Bagaj kapağı ağırlığı orta seviyedeydi.", "neutral"),
    ("Ayna sinyalleri çalışıyordu.", "neutral"),
    ("Park sensörü yoktu, kamera da yokmuş.", "neutral"),
    ("Vites geçişi hakkında bilgi verilmedi.", "neutral"),
    ("Araçta ekran boyutu küçükmüş.", "neutral"),
    ("Tavan kaplaması açık renkmiş.", "neutral"),
    ("Gösterge paneli klasik ibreliymiş.", "neutral"),
    ("Açma kapama tuşları büyük tasarlanmıştı.", "neutral"),
    ("Hoparlör sayısı belirtilmemişti.", "neutral"),
    ("Koltuk dikişleri dikkat çekici değildi.", "neutral"),
    ("Cam yüzeylerde film yoktu.", "neutral"),
    ("Model yılı güncel değildi.", "neutral"),
    ("Araçtan farklı sesler gelmedi.", "neutral"),
    ("Teker boşlukları çok belirgin değildi.", "neutral"),
    ("Bagaj iç döşemesi sade kalmıştı.", "neutral"),
    ("Araç yükseklik seviyesi değişmemiş.", "neutral"),
    ("Kabin tavanı düz ve sertti.", "neutral"),
    ("Far açma tuşu direksiyon altındaydı.", "neutral"),
    ("Far yüksekliği manuel ayarlanıyordu.", "neutral"),
    ("Gövde çizikleri yoktu.", "neutral"),
    ("Satış temsilcisi teknik detaylara girmedi.", "neutral"),
    ("Lastik basınç bilgisi verildi.", "neutral"),
    ("Araç teslimatı saatinde yapıldı.", "neutral"),
    ("Araçta döşeme rengi sadece griydi.", "neutral"),
    ("Kapı lastikleri tam oturmamıştı.", "neutral"),
    ("Ön cam görüş açısı yeterliydi.", "neutral"),
    ("Yedek parça fiyatı henüz belli değilmiş.", "neutral"),
    ("Koltuk başlıkları biraz sertti.", "neutral"),
    ("Donanım seviyesi giriş modelmiş.", "neutral"),
    ("Ön konsol sade tasarlanmış.", "neutral"),
    ("Arka camda buğu çözme vardı.", "neutral"),
    ("Yakıt tüketimi hakkında bilgi verilmedi.", "neutral"),
    ("Gövde bağlantıları sağlam görünüyor.", "neutral"),
    ("Araçta koltuk soğutma yokmuş.", "neutral"),
    ("Motor kapağı iç yalıtımsızdı.", "neutral"),
    ("İç tavan kumaşı yumuşaktı.", "neutral"),
    ("Klimanın sıcak ayarı geç algılıyordu.", "neutral"),
    ("Camların açılışı yavaştı.", "neutral"),
    ("Dış ayna camı düz yapılıydı.", "neutral"),
    ("Geri viteste ses gelmiyordu.", "neutral"),
    ("Gösterge ışıkları beyazdı.", "neutral"),
    ("Sürüş süresince fark edilir bir titreşim yoktu.", "neutral"),
    ("Koltuk sırt desteği ayarlanamıyordu.", "neutral"),
    ("Sürücü tarafı güneşlik aynasızdı.", "neutral"),
    ("Kapı çıtaları çok belirgin değildi.", "neutral"),
    ("Anahtar pili zayıfmış.", "neutral"),
    ("Fren hissi normal seviyedeydi.", "neutral"),
    ("Gövde gürültüsü azdı.", "neutral"),
    ("Vites kolu kısa tasarlanmıştı.", "neutral"),
    ("Bagaj açılışı yarı otomatikti.", "neutral"),
    ("Yol tutuşu hakkında yorum yapılmadı.", "neutral"),
    ("Silecek suyu hızlı bitti.", "neutral"),
    ("Ön cam yağmurda zor temizlendi.", "neutral"),
    ("Araç teslim formu eksiksizdi.", "neutral"),
    ("Araç plakası geç basıldı.", "neutral"),
    ("Teslim sonrası araç yıkanmıştı.", "neutral"),
    ("Kargo filesi yoktu.", "neutral"),
    ("Ayna içten karartmalı değilmiş.", "neutral"),
    ("Motor sesi testte duyulmadı.", "neutral"),
    ("İç mekan çok sessiz değildi.", "neutral"),
    ("Konsol ekranı mat yüzeyliydi.", "neutral"),
    ("Direksiyon derisi yapaymış.", "neutral"),
    ("Kasa tipi hatchback yazıyordu.", "neutral"),
    ("Teslim süreci normaldi.", "neutral"),
    ("Kapılar sürtünmeden kapanıyordu.", "neutral"),
    ("Fiyat listesi A4 olarak verildi.", "neutral"),
    ("Kol dayama bölmesi küçüktü.", "neutral"),
    ("Aracın menzili belirtilmemişti.", "neutral"),
    ("Model adı motor kapağındaydı.", "neutral"),
    ("Klimanın sesi yüksek değildi.", "neutral"),
    ("Yan camlar buğulanmadı.", "neutral"),
    ("Araç profili fazla çıkıntılı değildi.", "neutral"),
    ("Vites geçiş sesi yoktu.", "neutral"),
    ("Sürüş destek sistemleri anlatılmadı.", "neutral")
]

random.shuffle(yorumlar)
df1 = pd.DataFrame(yorumlar, columns=["yorum","etiket"])

df2 = pd.read_csv(
    "/Users/berkeekinci/Downloads/magaza_yorumlari_duygu_analizi.csv",
    encoding="utf-16",
    sep=","
)

df2 = df2.rename(columns={"Görüş": "yorum", "Durum": "etiket"})

df2["etiket"] = (
    df2["etiket"].astype(str)
    .str.strip()
    .map({"Olumlu": "positive", "Olumsuz": "negative", "Tarafsız": "neutral"})
)


df2 = df2.dropna(subset=["yorum", "etiket"])

merged_df = pd.concat([df1, df2], ignore_index=True)

# 1) Stopwords ve MorphAnalyzer
try:
    _ = stopwords.words("turkish")
except:
    nltk.download("stopwords")
tr_stop = set(stopwords.words("turkish"))
morph = MorphAnalyzer()

def tokenize(text: str):
    tokens = re.findall(r"\b\w+\b", str(text).lower(), re.UNICODE)
    tokens = [t for t in tokens if t not in tr_stop and len(t) > 1]
    lemmas = []
    for t in tokens:
        try:
            analyses = morph.analyze(t)
            if analyses:
                lemmas.append(analyses[0].lemma)
            else:
                lemmas.append(t)
        except:
            lemmas.append(t)
    return lemmas

# 2) TF-IDF ayarı
vectorizer = TfidfVectorizer(
    tokenizer=tokenize,
    preprocessor=None,
    lowercase=False,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

# 3) Model listesi
model_defs = {
    "NaiveBayes" : MultinomialNB(),
    "LogReg"     : LogisticRegression(max_iter=1000),
    "SVM"        : LinearSVC(),
    "RandomFor." : RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1),
    "MLP"        : MLPClassifier(hidden_layer_sizes=(128,), max_iter=500, random_state=42)
}

# 4) Eğitim veya kayıtlı modelleri yükle
results = {}
if os.path.exists("tfidf.pkl") and all(os.path.exists(f"{m}.pkl") for m in model_defs.keys()):
    print("📂 Kayıtlı modeller yüklendi.")
    with open("tfidf.pkl", "rb") as f:
        vectorizer = pickle.load(f)
    for name in model_defs.keys():
        with open(f"{name}.pkl", "rb") as f:
            results[name] = pickle.load(f)
else:
    print("⚙️ Eğitim yapılıyor...")
    X = vectorizer.fit_transform(merged_df["yorum"])
    y = merged_df["etiket"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    for name, model in model_defs.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        acc = accuracy_score(y_test, y_pred) * 100
        print(f"\n[{name}] Accuracy = %{acc:.2f}")
        print(classification_report(y_test, y_pred, zero_division=0))
        results[name] = model

    # Kaydet
    with open("tfidf.pkl", "wb") as f:
        pickle.dump(vectorizer, f)
    for name, model in results.items():
        with open(f"{name}.pkl", "wb") as f:
            pickle.dump(model, f)
    print("💾 Eğitim tamamlandı ve modeller kaydedildi.")

# 5) Kullanıcıdan yorum alıp test etme
ori_text = input("\nUzun bir yorum girin: ").strip()

parts = re.split(r'[.!?]+', ori_text)
parts = [p.strip() for p in parts if p.strip()]
print(f"\nYorum toplam {len(parts)} cümle içeriyor:\n")
for p in parts:
    print("•", p)

labels = {name: [] for name in results.keys()}
for p in parts:
    p_clean = " ".join(tokenize(p))
    vec = vectorizer.transform([p_clean])
    for name, model in results.items():
        labels[name].append(model.predict(vec)[0])

print("\n== Her cümlede tahminler ==")
for name, labs in labels.items():
    print(name, ":", labs)

print("\n== Çoğunluk kararı (full yorum) ==")
for name, labs in labels.items():
    most = Counter(labs).most_common(1)[0][0]
    print(f"{name} → {most}")